services:
  postgres:
    image: postgres:17-alpine
    container_name: finstream-postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      POSTGRES_DB: finstream_sso
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME:-finstream_sso}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - finstream-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U finstream_sso -d finstream_sso"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local

networks:
  finstream-network:
    driver: bridge
